### ISSUE TITLE
Network no longer trains correctly

### ISSUE THREAD

**Issue by mathildor** [www0wwwjs1/Matrix-Capsules-EM-Tensorflow#18]
Both a colleague and I have tried to run your network, but it doesn't train and gets stuck on loss 0.36. Maybe one of the latest updates caused this?

Btw, thanks for sharing your code!

**Comment by www0wwwjs1** [comment]
Could you tell me which script doesn't work and the specific parameters? I can check the code for bugs.

**Comment by mathildor** [comment]
I was running with mnist - `python3 train.py "mnist"`. I saw that you did an update so I just started a new training, and seems to be working :)

**Comment by www0wwwjs1** [comment]
Yes, I update the routing mechanism in the latest version. Everything should be ok this time😊.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Mathilde Ørstavik<mailto:notifications@github.com>
发送时间: 2018年1月27日 3:15
收件人: www0wwwjs1/Matrix-Capsules-EM-Tensorflow<mailto:Matrix-Capsules-EM-Tensorflow@noreply.github.com>
抄送: Suofei Zhang<mailto:zhangsuofei_1982@hotmail.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [www0wwwjs1/Matrix-Capsules-EM-Tensorflow] Network no longer trains correctly (#18)


I was running with mnist - python3 train.py "mnist". I saw that you did an update so I just started a new training, and seems to be working :)
